name: 'Continuous Integration'
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - v1
    tags-ignore:
      - v1.*

jobs:
  exercise-on-tier-1-platforms:
    strategy:
      matrix:
        implementation: ['abcl', 'sbcl']
        os: ['ubuntu-latest', 'macos-latest']
        include:
          - implementation: 'sbcl'
            os: 'windows-latest'
    runs-on: '${{ matrix.os }}'
    name: 'Exercise on Tier 1 Platform'
    steps:
      - uses: actions/checkout@v3
      - name: 'Install MacPorts'
        if: runner.os == 'macOS'
        uses: melusina-org/setup-macports@v1
      - uses: melusina-org/setup-common-lisp@v1
        with:
          implementation: '${{ matrix.implementation }}'
      - uses: melusina-org/setup-quicklisp@v1
        with:
          implementation: '${{ matrix.implementation }}'
          additional-systems: >-
            alexandria            
      - uses: ./
        with:
          implementation: '${{ matrix.implementation }}'
          system: 'alexandria'
          operation: 'asdf:compile-op'

  exercise-on-tier-2-platforms:
    needs: exercise-on-tier-1-platforms
    strategy:
      matrix:
        implementation: ['clisp', 'ecl', 'gcl']
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: '${{ matrix.os }}'
    name: 'Exercise on Tier 2 Platform'
    steps:
      - uses: actions/checkout@v3
      - name: 'Install MacPorts'
        if: runner.os == 'macOS'
        uses: melusina-org/setup-macports@v1
      - uses: melusina-org/setup-common-lisp@v1
        continue-on-error: true
        with:
          implementation: '${{ matrix.implementation }}'
      - uses: melusina-org/setup-quicklisp@v1
        continue-on-error: true
        with:
          implementation: '${{ matrix.implementation }}'
          additional-systems: >-
            alexandria            
      - uses: ./
        continue-on-error: true
        with:
          implementation: '${{ matrix.implementation }}'
          system: 'alexandria'
          operation: 'asdf:compile-op'
